name: Build & Deploy
on:
  push:
    branches-ignore:
      - '**'
    tags:
      - "v*"

jobs:
  build:
    name: Build & Deploy
    runs-on: windows-2019
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Build
        shell: cmd
        run: |
		  set OPENSSL_ROOT_DIR="C:\Program Files\OpenSSL"
          call build.bat
          mkdir dist
          copy build\Release\datachannel-static.lib dist

      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref_name }}

      - name: Upload assets
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./dist/datachannel-static.lib
          asset_name: datachannel.lib
          asset_content_type: application/octet-stream
